/* 계정 생성(관리자 계정으로 접속)*/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE ;

CREATE USER SPRING_KCH IDENTIFIED BY SPRING1234;

GRANT CONNECT, RESOURCE TO SPRING_KCH;

ALTER USER SPRING_KCH
DEFAULT TABLESPACE USERS
QUOTA 20M ON USERS;

--> 계정 생성 후 접속 방법(새 데이터 베이스) 추가

--------------------------------------------------------------------

/* SPRING 계정 접속 */
--  "" : 내부에 작성된 글(모양)그대로 인식 -> 대/소문자 구분
--> "" 작성 권장

-- CHAR(10)		 : 고정 길이 문자열 10바이트(최대 2000 바이트)
-- VARCHAR2(10)  : 가변 길이 문자열 10바이트(최대 4000 바이트)
-- NVARCHAR2(10) : 가변 길이 문자열 10글자(유니코드, 최대 4000 바이트)
-- CLOB	 : 가변 길이 문자열 (최대 4GB)

/* MEMBER 테이블 생성 */
CREATE TABLE "MEMBER"(
	"MEMBER_NO" 	  NUMBER CONSTRAINT "MEMBER_PK" PRIMARY KEY,
	"MEMBER_EMAIL"	  NVARCHAR2(50)  NOT NULL,
	"MEMBER_PW"       NVARCHAR2(100) NOT NULL,
	"MEMBER_NICKNAME" NVARCHAR2(10)  NOT NULL,
	"MEMBER_TEL"	  CHAR(11) 		 NOT NULL,
	"MEMBER_ADDRESS"  NVARCHAR2(150),
	"PROFILE_IMG"	  VARCHAR2(300),
	"ENROLL_DATE"	  DATE			 DEFAULT SYSDATE NOT NULL,
	"AUTHORITY"		  NUMBER 		 DEFAULT 1 CHECK("AUTHORITY" IN ('1','2') ),
	
	-- 회원 삭제 플래그 (DELETE로 데이터를 아주 지우지 않는다.)
	"MEMBER_DEL_FL"	  CHAR(1) DEFAULT 'N'  CHECK("MEMBER_DEL_FL" IN ('Y','N') )
	);

-- 회원 번호 시퀀스 만들기
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;



-- 샘플 회원데이터 삽입
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL,
	   'member01@naver.com',
	   '$2a$10$n0TIiJwZNXJKfwJk8uwyKuaKupO5l4m8rP05YCn/J8bmQAO/631d.',
	   '탈퇴시도01',
	   '01012341234',
	   NULL, NULL,
	   DEFAULT, DEFAULT, DEFAULT
	   );

COMMIT;

SELECT * FROM "MEMBER" m ;

DELETE  FROM "MEMBER" m 
WHERE MEMBER_EMAIL = '027620@naver.com'; -- 지우고 커밋해라........

-- 로그인 
-- 비밀번호 조회 : 가져와서 비교해야되니까
-- BCrypt 암호화 사용 중으로 DB에서 비밀번호 비교 불가능함.
-- 검색조건 : 이메일이 일치하는 회원 + 탈퇴 안한 회원
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_PW,
	 MEMBER_TEL , MEMBER_ADDRESS , PROFILE_IMG , AUTHORITY , 
	 TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH"시" MI"분" SS"초"') ENROLL_DATE  
FROM "MEMBER" 
WHERE MEMBER_EMAIL = ?
AND MEMBER_DEL_FL = 'N';


/* 이메일, 인증키 저장 테이블 생성 */

CREATE TABLE "TB_AUTH_KEY"(
	"KEY_NO" NUMBER PRIMARY KEY,
	"EMAIL"  NVARCHAR2(50) NOT NULL,
	"AUTH_KEY" CHAR(6) NOT NULL,
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL
	);

COMMENT ON COLUMN "TB_AUTH_KEY"."KEY_NO"		IS '인증키 구분 번호(시퀀스)';
COMMENT ON COLUMN "TB_AUTH_KEY"."EMAIL"			IS '인증 이메일';
COMMENT ON COLUMN "TB_AUTH_KEY"."AUTH_KEY"		IS '인증번호';
COMMENT ON COLUMN "TB_AUTH_KEY"."CREATE_TIME"	IS '인증 번호 생성 시간';

CREATE SEQUENCE SEQ_KEY_NO NOCACHE; -- 인증키 구분 번호 시퀀스

DROP TABLE "TB_AUTH-KEY";


SELECT * FROM TB_AUTH_KEY;

SELECT COUNT(*) 
FROM TB_AUTH_KEY
WHERE EMAIL = #{가입하려는 이메일 입력 값}
AND AUTH_KEY = #{위 이메일로 보낸 인증번호}


DELETE FROM TB_AUTH_KEY
WHERE EMAIL = '027620@naver.com';

SELECT *
FROM "MEMBER";

/* 파일 업로드 시험용 테이블 */
-- 파일 저장할 주소를 미리 정한 후 그 주소를 DB에 저장한다.
-- 파일을 DB에 직접 저장하지 않음(가능은 한데 비추천)
-- 파일 업로드 테스트용 테이블
CREATE TABLE "UPLOAD_FILE"(
	FILE_NO NUMBER PRIMARY KEY,
	FILE_PATH VARCHAR2(500) NOT NULL,
	FILE_ORIGINAL_NAME VARCHAR2(300) NOT NULL,
	FILE_RENAME VARCHAR2(100) NOT NULL,
	FILE_UPLOAD_DATE DATE DEFAULT SYSDATE,
	MEMBER_NO NUMBER REFERENCES "MEMBER"
);

COMMIT;

COMMENT ON COLUMN "UPLOAD_FILE".FILE_NO 		IS '파일 번호(PK)';
COMMENT ON COLUMN "FILE_PATH".FILE_PATH 			IS '클라이언트 요청 경로';
COMMENT ON COLUMN "FILE_ORIGINAL_NAME".FILE_ORIGINAL_NAME 	IS '파일 원본명';
COMMENT ON COLUMN "FILE_RENAME".FILE_RENAME 		IS '변경된 파일명';
COMMENT ON COLUMN "FILE_UPLOAD_DATE".FILE_UPLOAD_DATE 	IS '업로드한 날짜';
COMMENT ON COLUMN "MEMBER_NO".MEMBER_NO 			IS '파일을 올린 회원 번호 -> MEMBER테이블의 PK(MEMBER_NO)참조';

CREATE SEQUENCE SEQ_FILE_NO NOCACHE;


SELECT * FROM UPLOAD_FILE uf ;

-- 파일 이름은 변경해서 저장한다. 사용자가 정한 이름을 사용하게 되면 오류가 발생되기 때문


-- 파일 목록 조회


SELECT FILE_NO , FILE_PATH , FILE_ORIGINAL_NAME , FILE_RENAME,
	TO_CHAR(FILE_UPLOAD_DATE, 'YYYY-MM-DD') FILE_UPLOAD_DATE,
	MEMBER_NICKNAME
FROM "UPLOAD_FILE"
JOIN "MEMBER" USING(MEMBER_NO)
ORDER BY FILE_NO DESC ;


